"""schema_change_event

Revision ID: 0544a2fdf77a
Revises: 275bd4b1b642
Create Date: 2026-05-08 15:55:50.086997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0544a2fdf77a'
down_revision: Union[str, Sequence[str], None] = '275bd4b1b642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_runs', sa.Column('schema_changed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_runs', 'schema_changed')
    # ### end Alembic commands ###
