"""fix relationships

Revision ID: 277f0083bd87
Revises: e7cd3d2cd772
Create Date: 2026-05-08 10:47:57.498186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '277f0083bd87'
down_revision: Union[str, Sequence[str], None] = 'e7cd3d2cd772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_runs', sa.Column('baseline_version', sa.Integer(), nullable=False, server_default="1"))
    op.add_column('pipeline_runs', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('pipeline_runs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('pipeline_runs', 'ended_at')
    op.drop_column('pipeline_runs', 'started_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_runs', sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('pipeline_runs', sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('pipeline_runs', 'created_at')
    op.drop_column('pipeline_runs', 'file_path')
    op.drop_column('pipeline_runs', 'baseline_version')
    # ### end Alembic commands ###
