"""create baselines table

Revision ID: 37360ca62a2d
Revises: ecf3306d7482
Create Date: 2026-05-07 12:21:55.093339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37360ca62a2d'
down_revision: Union[str, Sequence[str], None] = 'ecf3306d7482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('schema', sa.JSON(), nullable=True),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baselines_id'), 'baselines', ['id'], unique=False)
    op.create_index(op.f('ix_baselines_model_id'), 'baselines', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_baselines_model_id'), table_name='baselines')
    op.drop_index(op.f('ix_baselines_id'), table_name='baselines')
    op.drop_table('baselines')
    # ### end Alembic commands ###
