"""update auth tables

Revision ID: 5283c559dd65
Revises: ecf3306d7482
Create Date: 2026-05-07 14:41:19.232657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5283c559dd65'
down_revision: Union[str, Sequence[str], None] = 'ecf3306d7482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_baselines_id'), table_name='baselines')
    op.drop_index(op.f('ix_baselines_model_id'), table_name='baselines')
    op.drop_table('baselines')
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.create_table('baselines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('profile', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('baselines_pkey'))
    )
    op.create_index(op.f('ix_baselines_model_id'), 'baselines', ['model_id'], unique=False)
    op.create_index(op.f('ix_baselines_id'), 'baselines', ['id'], unique=False)
    # ### end Alembic commands ###
