"""add column cleande_data

Revision ID: 58b7c4d61e48
Revises: f7148c3220c4
Create Date: 2026-05-08 11:57:29.011065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b7c4d61e48'
down_revision: Union[str, Sequence[str], None] = 'f7148c3220c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_runs', sa.Column('cleaned_data_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_runs', 'cleaned_data_path')
    # ### end Alembic commands ###
