"""create baselines table

Revision ID: 5ce83cf6eb23
Revises: 37360ca62a2d
Create Date: 2026-05-07 16:09:47.458589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce83cf6eb23'
down_revision: Union[str, Sequence[str], None] = '37360ca62a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS baselines (
            id SERIAL PRIMARY KEY,
            model_id VARCHAR,
            file_path VARCHAR,
            schema JSON,
            profile JSON,
            created_at TIMESTAMP WITHOUT TIME ZONE
        )
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_baselines_id ON baselines (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_baselines_model_id ON baselines (model_id)")
    op.execute("ALTER TABLE data_quality_findings ADD COLUMN IF NOT EXISTS model_id INTEGER")
    op.execute("ALTER TABLE data_quality_findings ADD COLUMN IF NOT EXISTS pipeline_run_id INTEGER")
    op.execute("ALTER TABLE data_quality_findings ADD COLUMN IF NOT EXISTS check_type VARCHAR")
    op.execute("ALTER TABLE data_quality_findings ADD COLUMN IF NOT EXISTS success BOOLEAN")
    op.execute("ALTER TABLE data_quality_findings ADD COLUMN IF NOT EXISTS details JSON")
    op.execute("ALTER TABLE data_quality_findings ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE")
    op.alter_column('data_quality_findings', 'column_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.execute("ALTER TABLE data_quality_findings DROP CONSTRAINT IF EXISTS data_quality_findings_run_id_fkey")
    op.execute("ALTER TABLE data_quality_findings DROP COLUMN IF EXISTS run_id")
    op.execute("ALTER TABLE data_quality_findings DROP COLUMN IF EXISTS description")
    op.execute("ALTER TABLE data_quality_findings DROP COLUMN IF EXISTS issue_type")
    # Auth columns are part of the production user contract. This migration was
    # generated from a partial model state and must not remove them on fresh DBs.
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS invite_token VARCHAR")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS invite_accepted BOOLEAN")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('invite_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('invite_accepted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('data_quality_findings', sa.Column('issue_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('data_quality_findings', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('data_quality_findings', sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('data_quality_findings_run_id_fkey'), 'data_quality_findings', 'pipeline_runs', ['run_id'], ['id'])
    op.alter_column('data_quality_findings', 'column_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('data_quality_findings', 'created_at')
    op.drop_column('data_quality_findings', 'details')
    op.drop_column('data_quality_findings', 'success')
    op.drop_column('data_quality_findings', 'check_type')
    op.drop_column('data_quality_findings', 'pipeline_run_id')
    op.drop_column('data_quality_findings', 'model_id')
    op.drop_index(op.f('ix_baselines_model_id'), table_name='baselines')
    op.drop_index(op.f('ix_baselines_id'), table_name='baselines')
    op.drop_table('baselines')
    # ### end Alembic commands ###
