"""create baselines table

Revision ID: 5ce83cf6eb23
Revises: 37360ca62a2d
Create Date: 2026-05-07 16:09:47.458589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce83cf6eb23'
down_revision: Union[str, Sequence[str], None] = '37360ca62a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('schema', sa.JSON(), nullable=True),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baselines_id'), 'baselines', ['id'], unique=False)
    op.create_index(op.f('ix_baselines_model_id'), 'baselines', ['model_id'], unique=False)
    op.add_column('data_quality_findings', sa.Column('model_id', sa.Integer(), nullable=True))
    op.add_column('data_quality_findings', sa.Column('pipeline_run_id', sa.Integer(), nullable=True))
    op.add_column('data_quality_findings', sa.Column('check_type', sa.String(), nullable=True))
    op.add_column('data_quality_findings', sa.Column('success', sa.Boolean(), nullable=True))
    op.add_column('data_quality_findings', sa.Column('details', sa.JSON(), nullable=True))
    op.add_column('data_quality_findings', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('data_quality_findings', 'column_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('data_quality_findings_run_id_fkey'), 'data_quality_findings', type_='foreignkey')
    op.drop_column('data_quality_findings', 'run_id')
    op.drop_column('data_quality_findings', 'description')
    op.drop_column('data_quality_findings', 'issue_type')
    op.drop_column('users', 'invite_accepted')
    op.drop_column('users', 'invite_token')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('invite_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('invite_accepted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('data_quality_findings', sa.Column('issue_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('data_quality_findings', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('data_quality_findings', sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('data_quality_findings_run_id_fkey'), 'data_quality_findings', 'pipeline_runs', ['run_id'], ['id'])
    op.alter_column('data_quality_findings', 'column_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('data_quality_findings', 'created_at')
    op.drop_column('data_quality_findings', 'details')
    op.drop_column('data_quality_findings', 'success')
    op.drop_column('data_quality_findings', 'check_type')
    op.drop_column('data_quality_findings', 'pipeline_run_id')
    op.drop_column('data_quality_findings', 'model_id')
    op.drop_index(op.f('ix_baselines_model_id'), table_name='baselines')
    op.drop_index(op.f('ix_baselines_id'), table_name='baselines')
    op.drop_table('baselines')
    # ### end Alembic commands ###
