"""add invite fields

Revision ID: 6e9893f5e93f
Revises: 5283c559dd65
Create Date: 2026-05-07 15:17:27.300773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e9893f5e93f'
down_revision: Union[str, Sequence[str], None] = '5283c559dd65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invite_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('invite_accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'invite_accepted')
    op.drop_column('users', 'invite_token')
    # ### end Alembic commands ###
