"""add drift and data quality tables

Revision ID: 958e2f2fc57f
Revises: 4eae204c385f
Create Date: 2026-04-29 14:09:59.654749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958e2f2fc57f'
down_revision: Union[str, Sequence[str], None] = '4eae204c385f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.String(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drift_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=False),
    sa.Column('drift_detected', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('incidents', sa.Column('finding_type', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('finding_id', sa.Integer(), nullable=True))
    op.drop_column('pipeline_runs', 'drift_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_runs', sa.Column('drift_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('incidents', 'finding_id')
    op.drop_column('incidents', 'finding_type')
    op.drop_table('drift_findings')
    op.drop_table('data_quality_findings')
    # ### end Alembic commands ###
