"""add drift and data quality findings

Revision ID: 9ee5afd39a99
Revises: 958e2f2fc57f
Create Date: 2026-04-29 14:14:32.513554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee5afd39a99'
down_revision: Union[str, Sequence[str], None] = '958e2f2fc57f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drift_findings', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.execute("""
    ALTER TABLE drift_findings
    ALTER COLUMN drift_detected
    TYPE BOOLEAN
    USING (drift_detected = 'yes')
""")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("""
        ALTER TABLE drift_findings
        ALTER COLUMN drift_detected
        TYPE VARCHAR
        USING CASE
            WHEN drift_detected = true THEN 'yes'
            ELSE 'no'
        END
    """)

    op.drop_column('drift_findings', 'created_at')
