"""add mlflow metadata to ml models

Revision ID: de420001643a
Revises: 9ee5afd39a99
Create Date: 2026-04-30 14:52:52.425602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de420001643a'
down_revision: Union[str, Sequence[str], None] = '9ee5afd39a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_models', sa.Column('mlflow_model_name', sa.String(), nullable=True))
    op.add_column('ml_models', sa.Column('mlflow_alias', sa.String(), nullable=True))
    op.add_column('ml_models', sa.Column('mlflow_run_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ml_models', 'mlflow_run_id')
    op.drop_column('ml_models', 'mlflow_alias')
    op.drop_column('ml_models', 'mlflow_model_name')
    # ### end Alembic commands ###
