"""relation added

Revision ID: e7cd3d2cd772
Revises: 529144411f43
Create Date: 2026-05-08 09:54:11.708092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7cd3d2cd772'
down_revision: Union[str, Sequence[str], None] = '529144411f43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'data_quality_findings', 'pipeline_runs', ['pipeline_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_quality_findings', type_='foreignkey')
    # ### end Alembic commands ###
