"""update auth tables

Revision ID: ecf3306d7482
Revises: 769ed1a45888
Create Date: 2026-05-07 10:14:49.100634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecf3306d7482'
down_revision: Union[str, Sequence[str], None] = '769ed1a45888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Older branches had these columns at this point in the migration chain.
    # Fresh local databases may not, so keep the migration restart-safe.
    op.execute("ALTER TABLE drift_findings DROP COLUMN IF EXISTS psi_score")
    op.execute("ALTER TABLE drift_findings DROP COLUMN IF EXISTS ks_pvalue")
    op.execute("ALTER TABLE drift_findings DROP COLUMN IF EXISTS ks_score")
    op.execute("ALTER TABLE drift_findings DROP COLUMN IF EXISTS severity")
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('otp_code', sa.String(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_constraint(op.f('users_tenant_id_fkey'), 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('users_tenant_id_fkey'), 'users', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'otp_code')
    op.drop_column('users', 'is_verified')
    op.add_column('drift_findings', sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('drift_findings', sa.Column('ks_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('drift_findings', sa.Column('ks_pvalue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('drift_findings', sa.Column('psi_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
