"""change field type

Revision ID: ed8427f56e4e
Revises: cf3a126e4402
Create Date: 2026-05-18 11:43:32.922090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed8427f56e4e'
down_revision: Union[str, Sequence[str], None] = 'cf3a126e4402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agent_runs_tenant_id_fkey'), 'agent_runs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('agent_runs_tenant_id_fkey'), 'agent_runs', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###
