"""add invite fields

Revision ID: f1728842a8e2
Revises: caffea0a19f8
Create Date: 2026-05-07 16:53:48.064397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1728842a8e2'
down_revision: Union[str, Sequence[str], None] = 'caffea0a19f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS baselines (
            id SERIAL PRIMARY KEY,
            model_id INTEGER,
            version INTEGER,
            schema JSON,
            profile JSON,
            status VARCHAR,
            is_active BOOLEAN,
            created_at TIMESTAMP WITHOUT TIME ZONE
        )
        """
    )
    op.execute("ALTER TABLE baselines ADD COLUMN IF NOT EXISTS version INTEGER")
    op.execute("ALTER TABLE baselines ADD COLUMN IF NOT EXISTS status VARCHAR")
    op.execute("ALTER TABLE baselines ADD COLUMN IF NOT EXISTS is_active BOOLEAN")
    op.execute("ALTER TABLE baselines ALTER COLUMN model_id TYPE INTEGER USING model_id::integer")
    op.execute("ALTER TABLE baselines ALTER COLUMN model_id SET NOT NULL")
    op.execute("ALTER TABLE baselines ALTER COLUMN version SET NOT NULL")
    op.execute("ALTER TABLE baselines ALTER COLUMN schema SET NOT NULL")
    op.execute("ALTER TABLE baselines ALTER COLUMN profile SET NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('baselines')
    # ### end Alembic commands ###
