artifact_location: file:///C:/Users/user1/Desktop/pipeline-doctor/backend/fastapi/300707/0
creation_time: 1778604376094
experiment_id: '0'
last_update_time: 1778604376094
lifecycle_stage: active
name: Default
trace_location: null
workspace: default
