# Generated by Django 6.0.4 on 2026-04-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinerun',
            name='model',
        ),
        migrations.RemoveField(
            model_name='predictionlog',
            name='run',
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
        migrations.DeleteModel(
            name='MLModel',
        ),
        migrations.DeleteModel(
            name='PipelineRun',
        ),
        migrations.DeleteModel(
            name='PredictionLog',
        ),
    ]
